### PR TITLE
Reorganize symbols (attempt to fix tests)

### PR DESCRIPTION
**Pull request by svetlyak40wt**

### CODE REVIEW

**Comment by kilianmh** [comment]
Is the Github CI Blackbox saving or stealing more time?

**Comment by svetlyak40wt** [comment]
@kilianmh I hate GitHub actions debugging.

Actually, there are tools like this one (https://github.com/mxschmitt/action-tmate) which allow to look inside the container. But environment will be different from what real code step sees.

**Comment by svetlyak40wt** [comment]
@kilianmh what I'm trying to debug is why my fix for quicklisp is not applied inside the action.

This small patch (https://github.com/40ants/quicklisp-client-fix) fixes the way how Quicklisp client loads package-inferred dependencies. For example, if you'll try to load `jsonrpc/client` from the environment where there is no code for jsonrpc, then quicklisp client will fail, because it is unaware about the `jsonrpc/client` system. However, he knows about the primary system `jsonrpc`. And my fix make quicklisp try to load `jsonrpc` system first in such case.

**Comment by svetlyak40wt** [comment]
Finally I was able to figure out the reason of this error:

```
; Loading "jsonrpc/server"

debugger invoked on a ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread
#<THREAD tid=5789 "main thread" RUNNING {1000E28093}>:
  Component "jsonrpc/server" not found
```

On CI qlfile is empty and tries to load jsonrpc from Quicklisp where we still have an old version of code and there is no jsonrpc/server file.

**Pull request merged**
