### PR TITLE
Fix: array type without items

### PR DESCRIPTION
**Pull request by kilianmh**
Till now a spec where `type` `array` is specified but no `items` results in an `error`. Now there is a check in `generate-result-transformation` for the presence of `items`. If not present, there will be no transformations.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Thank you!

**Comment by svetlyak40wt** [comment]
It is not necessary to update generated documentation files in the PR. They will be updated automatically when pull get merged into the "master" branch.

But adding a description of the changes into the `docs/changelog.lisp` is a good taste. This way we communicate to the users what we have done and what consequences these changes may entail. By the way, some users may subscribe on my ChangeLogs using RSS, here is [one for OpenRPC](https://40ants.com/openrpc/changelog.xml).

**Comment by kilianmh** [comment]
> But adding a description of the changes into the docs/changelog.lisp is a good taste.

Indeed, that is totally correct. Will try to remember that next time.
 
Also I would have updated the tests but I thought it makes more sense after #12 is solved.

**Comment by svetlyak40wt** [comment]
Great! Thank you!

**Pull request merged**
